# Generated by Django 5.2.17 on 2026-09-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_testcase_options_alter_submission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supabase_uid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
