# Generated by Django 5.2.17 on 2026-09-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_supabase_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="passing_score",
            field=models.DecimalField(decimal_places=2, default=60, max_digits=5),
        ),
        migrations.AddField(
            model_name="exercise",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="max_possible_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name="submission",
            name="passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="submission",
            name="total_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_CHOICE", "Multiple choice"),
                            ("BOOLEAN", "Boolean"),
                            ("NUMERICAL", "Numerical"),
                            ("CODE_CHALLENGE", "Code challenge"),
                        ],
                        max_length=30,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.JSONField()),
                (
                    "code_language_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("test_cases", models.JSONField(blank=True, default=list)),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=1, max_digits=7),
                ),
                ("explanation", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_answer", models.JSONField(blank=True, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "score_awarded",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ("judge0_output", models.JSONField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_answers",
                        to="api.question",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.submission",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "question"),
                        name="unique_submission_question",
                    )
                ],
            },
        ),
    ]
