# Generated by Django 5.2.17 on 2026-09-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_exercise_is_active_exercise_passing_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.CharField(
                choices=[
                    ("database", "Base de datos"),
                    ("python", "Python"),
                    ("react", "React"),
                    ("git", "Git"),
                    ("terminal", "Terminal"),
                ],
                default="python",
                max_length=20,
            ),
        ),
    ]
