# Generated by Django 5.2.17 on 2026-09-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_exercise_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="is_exam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exercise",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Inicial"),
                    ("intermediate", "Intermedio"),
                    ("advanced", "Avanzado"),
                    ("expert", "Experto"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="learning_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Inicial"),
                    ("intermediate", "Intermedio"),
                    ("advanced", "Avanzado"),
                    ("expert", "Experto"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
    ]
